### ISSUE TITLE
Crash upon startup (1.20.1)

### ISSUE THREAD

**Issue by StellaBiscuit** [TheLMiffy1111/JAOPCAGT#1]
MC Version : 1.20.1
JAOPCA Version : JAOPCA-1.20.1-4.4.7.8.jar
JAOPCAGT Version : Both 1.20.1 version
GT Version : gtceu-forge-1.20.1-1.0.20.b.jar

Crash Report : [crash-2024-01-12_06.44.50-client.txt](https://github.com/TheLMiffy1111/JAOPCAGT/files/13918599/crash-2024-01-12_06.44.50-client.txt)

**Comment by StellaBiscuit** [comment]
Only happens with the newest version of GT, not with 1.0.19b, looking at the change log, they changed the registration, causing the crash

**Comment by TheLMiffy1111** [comment]
Should be fixed in 2.0.0.2 / 2.1.0.2
